# Generated by Django 4.1.4 on 2022-12-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.BooleanField()),
                ("age", models.IntegerField()),
            ],
        ),
    ]
