# Generated by Django 4.1.4 on 2022-12-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="birth_date", field=models.DateField(null=True),
        ),
    ]
