# Generated by Django 4.1.4 on 2022-12-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="event", name="age", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="event", name="gender", field=models.BooleanField(null=True),
        ),
    ]
