# Generated by Django 4.1.4 on 2022-12-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0003_event_name_alter_event_age_alter_event_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("birth_date", models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(name="Age",),
        migrations.DeleteModel(name="Event",),
    ]
