# Generated by Django 4.1.4 on 2022-12-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0004_user_delete_age_delete_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="birth_date", field=models.IntegerField(),
        ),
    ]
